spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MONEVI_GMAIL_USERNAME}
    password: ${MONEVI_GMAIL_PASSWORD}
    smtpAuth: true
    smtpStartTlsEnable: true
    mailDebug: true
    templatePath: templates/email/
  cache:
    jcache:
      config: classpath:ehcache.xml

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 10
              unit: seconds

monevi:
  jwt:
    secretKey: ${MONEVI_SECRET_KEY}
    access:
      token:
        expiration-time: 18000000
  redirect:
    reset-password:
      url: ${MONEVI_FRONT_END_URL}