spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test123
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: monevi.test@gmail.com
    password: test123 # ask first before using this value
    smtpAuth: true
    smtpStartTlsEnable: true
    mailDebug: true
    templatePath: templates/email/
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  cache:
    jcache:
      config: classpath:ehcache.xml

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 10
              unit: seconds

monevi:
  jwt:
    secretKey: monevi-secret-key
    access:
      token:
        expiration-time: 18000000 # in milliseconds, current: 5 hrs
  redirect:
    reset-password:
      url: https://www.google.com/
