spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test123

monevi:
  jwt:
    secretKey: monevi-secret-key
    access:
      token:
        expiration-time: 18000000 # in milliseconds, current: 5 hrs
